---

name: Release on PyPI

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements_build.txt >/dev/null
          pip install -r requirements.txt >/dev/null

      - name: Building
        run: |
          git reset --hard

          echo "$(git describe --abbrev=0 --tags)" > VERSION
          python3 -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
